# Data-only container
datamysql:
  image: mysql:5.5
  entrypoint: /bin/echo
  command: MySQL data-only container

# Data-only container
datadrupal:
  image: zaporylie/drupal:2
  entrypoint: /bin/echo
  command: APP data-only container

# MySQL service container
mysql:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: secret_password

# Drupal container
drupal:
  build: .
  environment:
    DB_NAME: drupal
    DB_USER: drupal
    DB_PASSWORD: drupal
    DRUPAL_PROFILE: standard
    DRUPAL_SUBDIR: default
    DB_SYNC_METHOD: auto
    DB_SYNC_DRUSH_FROM: dev
  ports:
    - "80"
    - "22"
