# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty64"
  config.vm.provision :shell, :path => "provision.sh", :args => ENV['SHELL_ARGS']
  config.vm.network :private_network, ip: '10.254.254.254'
  config.vm.hostname = "vagrant.dev"
  config.hostsupdater.aliases = ["drupal1.dev", "drupal2.dev", "drupal3.dev", "drupal4.dev", "drupal5.dev", "drupal6.dev", "drupal7.dev", "drupal8.dev", "drupal9.dev", "drupal10.dev", "drupal11.dev", "drupal12.dev"]
  config.ssh.forward_agent = true

  config.vm.synced_folder "./", "/home/share",
    id: "core",
    :nfs => true,
    :mount_options => ['nolock,vers=3,udp']

  config.vm.synced_folder "~/.ssh", "/home/identity",
    id: "identity",
    :nfs => true,
    :mount_options => ['nolock,vers=3,udp']

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

end
